package com.weshare.snow.mapper;

import com.weshare.snow.model.CtcAdvet;
import com.weshare.snow.model.CtcAdvetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtcAdvetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int countByExample(CtcAdvetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int deleteByExample(CtcAdvetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int insert(CtcAdvet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int insertSelective(CtcAdvet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    List<CtcAdvet> selectByExample(CtcAdvetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    CtcAdvet selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CtcAdvet record, @Param("example") CtcAdvetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CtcAdvet record, @Param("example") CtcAdvetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CtcAdvet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_advet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CtcAdvet record);
}