package com.weshare.snow.mapper;

import com.weshare.snow.model.CtcPrroduct;
import com.weshare.snow.model.CtcPrroductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtcPrroductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int countByExample(CtcPrroductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int deleteByExample(CtcPrroductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int insert(CtcPrroduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int insertSelective(CtcPrroduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    List<CtcPrroduct> selectByExample(CtcPrroductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    CtcPrroduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CtcPrroduct record, @Param("example") CtcPrroductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CtcPrroduct record, @Param("example") CtcPrroductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CtcPrroduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CtcPrroduct record);
}