package com.weshare.snow.mapper;

import com.weshare.snow.model.CtcStriking;
import com.weshare.snow.model.CtcStrikingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtcStrikingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int countByExample(CtcStrikingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int deleteByExample(CtcStrikingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int insert(CtcStriking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int insertSelective(CtcStriking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    List<CtcStriking> selectByExample(CtcStrikingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    CtcStriking selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CtcStriking record, @Param("example") CtcStrikingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CtcStriking record, @Param("example") CtcStrikingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CtcStriking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_striking
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CtcStriking record);
}