package com.weshare.snow.mapper;

import com.weshare.snow.model.CtcSmsLog;
import com.weshare.snow.model.CtcSmsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtcSmsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int countByExample(CtcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int deleteByExample(CtcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int insert(CtcSmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int insertSelective(CtcSmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    List<CtcSmsLog> selectByExample(CtcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    CtcSmsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CtcSmsLog record, @Param("example") CtcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CtcSmsLog record, @Param("example") CtcSmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CtcSmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_sms_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CtcSmsLog record);
}