package com.weshare.snow.mapper;

import com.weshare.snow.model.CtcUvLog;
import com.weshare.snow.model.CtcUvLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtcUvLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int countByExample(CtcUvLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int deleteByExample(CtcUvLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int insert(CtcUvLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int insertSelective(CtcUvLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    List<CtcUvLog> selectByExample(CtcUvLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    CtcUvLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CtcUvLog record, @Param("example") CtcUvLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CtcUvLog record, @Param("example") CtcUvLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CtcUvLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_uv_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CtcUvLog record);
}