package com.weshare.snow.model;

import java.util.Date;

public class CtcAdvet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.advet_url
     *
     * @mbggenerated
     */
    private String advetUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.advet_jump_url
     *
     * @mbggenerated
     */
    private String advetJumpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_advet.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.id
     *
     * @return the value of ctc_advet.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.id
     *
     * @param id the value for ctc_advet.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.create_by
     *
     * @return the value of ctc_advet.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.create_by
     *
     * @param createBy the value for ctc_advet.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.create_date
     *
     * @return the value of ctc_advet.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.create_date
     *
     * @param createDate the value for ctc_advet.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.update_by
     *
     * @return the value of ctc_advet.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.update_by
     *
     * @param updateBy the value for ctc_advet.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.update_date
     *
     * @return the value of ctc_advet.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.update_date
     *
     * @param updateDate the value for ctc_advet.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.remarks
     *
     * @return the value of ctc_advet.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.remarks
     *
     * @param remarks the value for ctc_advet.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.del_flag
     *
     * @return the value of ctc_advet.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.del_flag
     *
     * @param delFlag the value for ctc_advet.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.advet_url
     *
     * @return the value of ctc_advet.advet_url
     *
     * @mbggenerated
     */
    public String getAdvetUrl() {
        return advetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.advet_url
     *
     * @param advetUrl the value for ctc_advet.advet_url
     *
     * @mbggenerated
     */
    public void setAdvetUrl(String advetUrl) {
        this.advetUrl = advetUrl == null ? null : advetUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.advet_jump_url
     *
     * @return the value of ctc_advet.advet_jump_url
     *
     * @mbggenerated
     */
    public String getAdvetJumpUrl() {
        return advetJumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.advet_jump_url
     *
     * @param advetJumpUrl the value for ctc_advet.advet_jump_url
     *
     * @mbggenerated
     */
    public void setAdvetJumpUrl(String advetJumpUrl) {
        this.advetJumpUrl = advetJumpUrl == null ? null : advetJumpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_advet.product_id
     *
     * @return the value of ctc_advet.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_advet.product_id
     *
     * @param productId the value for ctc_advet.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    private String voAdvetUrl;

    public String getVoAdvetUrl() {
        //return voAdvetUrl;
        return new StringBuffer("").append("http://daichao.dajiabuy.cn").append("/data/web/upload/daichao/").append(advetUrl).toString();
    }

    public void setVoAdvetUrl(String voAdvetUrl) {
        this.voAdvetUrl = voAdvetUrl;
    }
}