package com.weshare.snow.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtcPrroductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public CtcPrroductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIsNull() {
            addCriterion("product_category_id is null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIsNotNull() {
            addCriterion("product_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdEqualTo(String value) {
            addCriterion("product_category_id =", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotEqualTo(String value) {
            addCriterion("product_category_id <>", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdGreaterThan(String value) {
            addCriterion("product_category_id >", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_category_id >=", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLessThan(String value) {
            addCriterion("product_category_id <", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("product_category_id <=", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdLike(String value) {
            addCriterion("product_category_id like", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotLike(String value) {
            addCriterion("product_category_id not like", value, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdIn(List<String> values) {
            addCriterion("product_category_id in", values, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotIn(List<String> values) {
            addCriterion("product_category_id not in", values, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdBetween(String value1, String value2) {
            addCriterion("product_category_id between", value1, value2, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIdNotBetween(String value1, String value2) {
            addCriterion("product_category_id not between", value1, value2, "productCategoryId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andQuotaIsNull() {
            addCriterion("quota is null");
            return (Criteria) this;
        }

        public Criteria andQuotaIsNotNull() {
            addCriterion("quota is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaEqualTo(String value) {
            addCriterion("quota =", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaNotEqualTo(String value) {
            addCriterion("quota <>", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaGreaterThan(String value) {
            addCriterion("quota >", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaGreaterThanOrEqualTo(String value) {
            addCriterion("quota >=", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaLessThan(String value) {
            addCriterion("quota <", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaLessThanOrEqualTo(String value) {
            addCriterion("quota <=", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaLike(String value) {
            addCriterion("quota like", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaNotLike(String value) {
            addCriterion("quota not like", value, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaIn(List<String> values) {
            addCriterion("quota in", values, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaNotIn(List<String> values) {
            addCriterion("quota not in", values, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaBetween(String value1, String value2) {
            addCriterion("quota between", value1, value2, "quota");
            return (Criteria) this;
        }

        public Criteria andQuotaNotBetween(String value1, String value2) {
            addCriterion("quota not between", value1, value2, "quota");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("rate is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("rate is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(String value) {
            addCriterion("rate =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(String value) {
            addCriterion("rate <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(String value) {
            addCriterion("rate >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(String value) {
            addCriterion("rate >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(String value) {
            addCriterion("rate <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(String value) {
            addCriterion("rate <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLike(String value) {
            addCriterion("rate like", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotLike(String value) {
            addCriterion("rate not like", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<String> values) {
            addCriterion("rate in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<String> values) {
            addCriterion("rate not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(String value1, String value2) {
            addCriterion("rate between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(String value1, String value2) {
            addCriterion("rate not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeIsNull() {
            addCriterion("ctc_describe is null");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeIsNotNull() {
            addCriterion("ctc_describe is not null");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeEqualTo(String value) {
            addCriterion("ctc_describe =", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeNotEqualTo(String value) {
            addCriterion("ctc_describe <>", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeGreaterThan(String value) {
            addCriterion("ctc_describe >", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("ctc_describe >=", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeLessThan(String value) {
            addCriterion("ctc_describe <", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeLessThanOrEqualTo(String value) {
            addCriterion("ctc_describe <=", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeLike(String value) {
            addCriterion("ctc_describe like", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeNotLike(String value) {
            addCriterion("ctc_describe not like", value, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeIn(List<String> values) {
            addCriterion("ctc_describe in", values, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeNotIn(List<String> values) {
            addCriterion("ctc_describe not in", values, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeBetween(String value1, String value2) {
            addCriterion("ctc_describe between", value1, value2, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andCtcDescribeNotBetween(String value1, String value2) {
            addCriterion("ctc_describe not between", value1, value2, "ctcDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeIsNull() {
            addCriterion("details_describe is null");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeIsNotNull() {
            addCriterion("details_describe is not null");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeEqualTo(String value) {
            addCriterion("details_describe =", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeNotEqualTo(String value) {
            addCriterion("details_describe <>", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeGreaterThan(String value) {
            addCriterion("details_describe >", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("details_describe >=", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeLessThan(String value) {
            addCriterion("details_describe <", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeLessThanOrEqualTo(String value) {
            addCriterion("details_describe <=", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeLike(String value) {
            addCriterion("details_describe like", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeNotLike(String value) {
            addCriterion("details_describe not like", value, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeIn(List<String> values) {
            addCriterion("details_describe in", values, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeNotIn(List<String> values) {
            addCriterion("details_describe not in", values, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeBetween(String value1, String value2) {
            addCriterion("details_describe between", value1, value2, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andDetailsDescribeNotBetween(String value1, String value2) {
            addCriterion("details_describe not between", value1, value2, "detailsDescribe");
            return (Criteria) this;
        }

        public Criteria andApplyNumsIsNull() {
            addCriterion("apply_nums is null");
            return (Criteria) this;
        }

        public Criteria andApplyNumsIsNotNull() {
            addCriterion("apply_nums is not null");
            return (Criteria) this;
        }

        public Criteria andApplyNumsEqualTo(Integer value) {
            addCriterion("apply_nums =", value, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsNotEqualTo(Integer value) {
            addCriterion("apply_nums <>", value, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsGreaterThan(Integer value) {
            addCriterion("apply_nums >", value, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_nums >=", value, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsLessThan(Integer value) {
            addCriterion("apply_nums <", value, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsLessThanOrEqualTo(Integer value) {
            addCriterion("apply_nums <=", value, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsIn(List<Integer> values) {
            addCriterion("apply_nums in", values, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsNotIn(List<Integer> values) {
            addCriterion("apply_nums not in", values, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsBetween(Integer value1, Integer value2) {
            addCriterion("apply_nums between", value1, value2, "applyNums");
            return (Criteria) this;
        }

        public Criteria andApplyNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_nums not between", value1, value2, "applyNums");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeIsNull() {
            addCriterion("fastest_loan_time is null");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeIsNotNull() {
            addCriterion("fastest_loan_time is not null");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeEqualTo(String value) {
            addCriterion("fastest_loan_time =", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeNotEqualTo(String value) {
            addCriterion("fastest_loan_time <>", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeGreaterThan(String value) {
            addCriterion("fastest_loan_time >", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeGreaterThanOrEqualTo(String value) {
            addCriterion("fastest_loan_time >=", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeLessThan(String value) {
            addCriterion("fastest_loan_time <", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeLessThanOrEqualTo(String value) {
            addCriterion("fastest_loan_time <=", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeLike(String value) {
            addCriterion("fastest_loan_time like", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeNotLike(String value) {
            addCriterion("fastest_loan_time not like", value, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeIn(List<String> values) {
            addCriterion("fastest_loan_time in", values, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeNotIn(List<String> values) {
            addCriterion("fastest_loan_time not in", values, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeBetween(String value1, String value2) {
            addCriterion("fastest_loan_time between", value1, value2, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andFastestLoanTimeNotBetween(String value1, String value2) {
            addCriterion("fastest_loan_time not between", value1, value2, "fastestLoanTime");
            return (Criteria) this;
        }

        public Criteria andSuccessRateIsNull() {
            addCriterion("success_rate is null");
            return (Criteria) this;
        }

        public Criteria andSuccessRateIsNotNull() {
            addCriterion("success_rate is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessRateEqualTo(String value) {
            addCriterion("success_rate =", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateNotEqualTo(String value) {
            addCriterion("success_rate <>", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateGreaterThan(String value) {
            addCriterion("success_rate >", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateGreaterThanOrEqualTo(String value) {
            addCriterion("success_rate >=", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateLessThan(String value) {
            addCriterion("success_rate <", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateLessThanOrEqualTo(String value) {
            addCriterion("success_rate <=", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateLike(String value) {
            addCriterion("success_rate like", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateNotLike(String value) {
            addCriterion("success_rate not like", value, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateIn(List<String> values) {
            addCriterion("success_rate in", values, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateNotIn(List<String> values) {
            addCriterion("success_rate not in", values, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateBetween(String value1, String value2) {
            addCriterion("success_rate between", value1, value2, "successRate");
            return (Criteria) this;
        }

        public Criteria andSuccessRateNotBetween(String value1, String value2) {
            addCriterion("success_rate not between", value1, value2, "successRate");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeIsNull() {
            addCriterion("quota_range is null");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeIsNotNull() {
            addCriterion("quota_range is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeEqualTo(String value) {
            addCriterion("quota_range =", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeNotEqualTo(String value) {
            addCriterion("quota_range <>", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeGreaterThan(String value) {
            addCriterion("quota_range >", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeGreaterThanOrEqualTo(String value) {
            addCriterion("quota_range >=", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeLessThan(String value) {
            addCriterion("quota_range <", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeLessThanOrEqualTo(String value) {
            addCriterion("quota_range <=", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeLike(String value) {
            addCriterion("quota_range like", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeNotLike(String value) {
            addCriterion("quota_range not like", value, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeIn(List<String> values) {
            addCriterion("quota_range in", values, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeNotIn(List<String> values) {
            addCriterion("quota_range not in", values, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeBetween(String value1, String value2) {
            addCriterion("quota_range between", value1, value2, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andQuotaRangeNotBetween(String value1, String value2) {
            addCriterion("quota_range not between", value1, value2, "quotaRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeIsNull() {
            addCriterion("term_range is null");
            return (Criteria) this;
        }

        public Criteria andTermRangeIsNotNull() {
            addCriterion("term_range is not null");
            return (Criteria) this;
        }

        public Criteria andTermRangeEqualTo(String value) {
            addCriterion("term_range =", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeNotEqualTo(String value) {
            addCriterion("term_range <>", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeGreaterThan(String value) {
            addCriterion("term_range >", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeGreaterThanOrEqualTo(String value) {
            addCriterion("term_range >=", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeLessThan(String value) {
            addCriterion("term_range <", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeLessThanOrEqualTo(String value) {
            addCriterion("term_range <=", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeLike(String value) {
            addCriterion("term_range like", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeNotLike(String value) {
            addCriterion("term_range not like", value, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeIn(List<String> values) {
            addCriterion("term_range in", values, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeNotIn(List<String> values) {
            addCriterion("term_range not in", values, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeBetween(String value1, String value2) {
            addCriterion("term_range between", value1, value2, "termRange");
            return (Criteria) this;
        }

        public Criteria andTermRangeNotBetween(String value1, String value2) {
            addCriterion("term_range not between", value1, value2, "termRange");
            return (Criteria) this;
        }

        public Criteria andDateRateIsNull() {
            addCriterion("date_rate is null");
            return (Criteria) this;
        }

        public Criteria andDateRateIsNotNull() {
            addCriterion("date_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDateRateEqualTo(String value) {
            addCriterion("date_rate =", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateNotEqualTo(String value) {
            addCriterion("date_rate <>", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateGreaterThan(String value) {
            addCriterion("date_rate >", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateGreaterThanOrEqualTo(String value) {
            addCriterion("date_rate >=", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateLessThan(String value) {
            addCriterion("date_rate <", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateLessThanOrEqualTo(String value) {
            addCriterion("date_rate <=", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateLike(String value) {
            addCriterion("date_rate like", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateNotLike(String value) {
            addCriterion("date_rate not like", value, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateIn(List<String> values) {
            addCriterion("date_rate in", values, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateNotIn(List<String> values) {
            addCriterion("date_rate not in", values, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateBetween(String value1, String value2) {
            addCriterion("date_rate between", value1, value2, "dateRate");
            return (Criteria) this;
        }

        public Criteria andDateRateNotBetween(String value1, String value2) {
            addCriterion("date_rate not between", value1, value2, "dateRate");
            return (Criteria) this;
        }

        public Criteria andApplyProcessIsNull() {
            addCriterion("apply_process is null");
            return (Criteria) this;
        }

        public Criteria andApplyProcessIsNotNull() {
            addCriterion("apply_process is not null");
            return (Criteria) this;
        }

        public Criteria andApplyProcessEqualTo(String value) {
            addCriterion("apply_process =", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessNotEqualTo(String value) {
            addCriterion("apply_process <>", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessGreaterThan(String value) {
            addCriterion("apply_process >", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessGreaterThanOrEqualTo(String value) {
            addCriterion("apply_process >=", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessLessThan(String value) {
            addCriterion("apply_process <", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessLessThanOrEqualTo(String value) {
            addCriterion("apply_process <=", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessLike(String value) {
            addCriterion("apply_process like", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessNotLike(String value) {
            addCriterion("apply_process not like", value, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessIn(List<String> values) {
            addCriterion("apply_process in", values, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessNotIn(List<String> values) {
            addCriterion("apply_process not in", values, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessBetween(String value1, String value2) {
            addCriterion("apply_process between", value1, value2, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyProcessNotBetween(String value1, String value2) {
            addCriterion("apply_process not between", value1, value2, "applyProcess");
            return (Criteria) this;
        }

        public Criteria andApplyConditionIsNull() {
            addCriterion("apply_condition is null");
            return (Criteria) this;
        }

        public Criteria andApplyConditionIsNotNull() {
            addCriterion("apply_condition is not null");
            return (Criteria) this;
        }

        public Criteria andApplyConditionEqualTo(String value) {
            addCriterion("apply_condition =", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionNotEqualTo(String value) {
            addCriterion("apply_condition <>", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionGreaterThan(String value) {
            addCriterion("apply_condition >", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionGreaterThanOrEqualTo(String value) {
            addCriterion("apply_condition >=", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionLessThan(String value) {
            addCriterion("apply_condition <", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionLessThanOrEqualTo(String value) {
            addCriterion("apply_condition <=", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionLike(String value) {
            addCriterion("apply_condition like", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionNotLike(String value) {
            addCriterion("apply_condition not like", value, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionIn(List<String> values) {
            addCriterion("apply_condition in", values, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionNotIn(List<String> values) {
            addCriterion("apply_condition not in", values, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionBetween(String value1, String value2) {
            addCriterion("apply_condition between", value1, value2, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyConditionNotBetween(String value1, String value2) {
            addCriterion("apply_condition not between", value1, value2, "applyCondition");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialIsNull() {
            addCriterion("apply_material is null");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialIsNotNull() {
            addCriterion("apply_material is not null");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialEqualTo(String value) {
            addCriterion("apply_material =", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialNotEqualTo(String value) {
            addCriterion("apply_material <>", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialGreaterThan(String value) {
            addCriterion("apply_material >", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("apply_material >=", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialLessThan(String value) {
            addCriterion("apply_material <", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialLessThanOrEqualTo(String value) {
            addCriterion("apply_material <=", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialLike(String value) {
            addCriterion("apply_material like", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialNotLike(String value) {
            addCriterion("apply_material not like", value, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialIn(List<String> values) {
            addCriterion("apply_material in", values, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialNotIn(List<String> values) {
            addCriterion("apply_material not in", values, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialBetween(String value1, String value2) {
            addCriterion("apply_material between", value1, value2, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andApplyMaterialNotBetween(String value1, String value2) {
            addCriterion("apply_material not between", value1, value2, "applyMaterial");
            return (Criteria) this;
        }

        public Criteria andNewProductIsNull() {
            addCriterion("new_product is null");
            return (Criteria) this;
        }

        public Criteria andNewProductIsNotNull() {
            addCriterion("new_product is not null");
            return (Criteria) this;
        }

        public Criteria andNewProductEqualTo(String value) {
            addCriterion("new_product =", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductNotEqualTo(String value) {
            addCriterion("new_product <>", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductGreaterThan(String value) {
            addCriterion("new_product >", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductGreaterThanOrEqualTo(String value) {
            addCriterion("new_product >=", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductLessThan(String value) {
            addCriterion("new_product <", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductLessThanOrEqualTo(String value) {
            addCriterion("new_product <=", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductLike(String value) {
            addCriterion("new_product like", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductNotLike(String value) {
            addCriterion("new_product not like", value, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductIn(List<String> values) {
            addCriterion("new_product in", values, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductNotIn(List<String> values) {
            addCriterion("new_product not in", values, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductBetween(String value1, String value2) {
            addCriterion("new_product between", value1, value2, "newProduct");
            return (Criteria) this;
        }

        public Criteria andNewProductNotBetween(String value1, String value2) {
            addCriterion("new_product not between", value1, value2, "newProduct");
            return (Criteria) this;
        }

        public Criteria andJumpUrlIsNull() {
            addCriterion("jump_url is null");
            return (Criteria) this;
        }

        public Criteria andJumpUrlIsNotNull() {
            addCriterion("jump_url is not null");
            return (Criteria) this;
        }

        public Criteria andJumpUrlEqualTo(String value) {
            addCriterion("jump_url =", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotEqualTo(String value) {
            addCriterion("jump_url <>", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlGreaterThan(String value) {
            addCriterion("jump_url >", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlGreaterThanOrEqualTo(String value) {
            addCriterion("jump_url >=", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlLessThan(String value) {
            addCriterion("jump_url <", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlLessThanOrEqualTo(String value) {
            addCriterion("jump_url <=", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlLike(String value) {
            addCriterion("jump_url like", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotLike(String value) {
            addCriterion("jump_url not like", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlIn(List<String> values) {
            addCriterion("jump_url in", values, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotIn(List<String> values) {
            addCriterion("jump_url not in", values, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlBetween(String value1, String value2) {
            addCriterion("jump_url between", value1, value2, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotBetween(String value1, String value2) {
            addCriterion("jump_url not between", value1, value2, "jumpUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctc_product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctc_product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}