package com.weshare.snow.model;

import java.util.Date;

public class CtcPrroduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.product_category_id
     *
     * @mbggenerated
     */
    private String productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.quota
     *
     * @mbggenerated
     */
    private String quota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.rate
     *
     * @mbggenerated
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.ctc_describe
     *
     * @mbggenerated
     */
    private String ctcDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.details_describe
     *
     * @mbggenerated
     */
    private String detailsDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.apply_nums
     *
     * @mbggenerated
     */
    private Integer applyNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.fastest_loan_time
     *
     * @mbggenerated
     */
    private String fastestLoanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.success_rate
     *
     * @mbggenerated
     */
    private String successRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.quota_range
     *
     * @mbggenerated
     */
    private String quotaRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.term_range
     *
     * @mbggenerated
     */
    private String termRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.date_rate
     *
     * @mbggenerated
     */
    private String dateRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.apply_process
     *
     * @mbggenerated
     */
    private String applyProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.apply_condition
     *
     * @mbggenerated
     */
    private String applyCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.apply_material
     *
     * @mbggenerated
     */
    private String applyMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.new_product
     *
     * @mbggenerated
     */
    private String newProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_product.jump_url
     *
     * @mbggenerated
     */
    private String jumpUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.id
     *
     * @return the value of ctc_product.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.id
     *
     * @param id the value for ctc_product.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.create_by
     *
     * @return the value of ctc_product.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.create_by
     *
     * @param createBy the value for ctc_product.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.create_date
     *
     * @return the value of ctc_product.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.create_date
     *
     * @param createDate the value for ctc_product.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.update_by
     *
     * @return the value of ctc_product.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.update_by
     *
     * @param updateBy the value for ctc_product.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.update_date
     *
     * @return the value of ctc_product.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.update_date
     *
     * @param updateDate the value for ctc_product.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.remarks
     *
     * @return the value of ctc_product.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.remarks
     *
     * @param remarks the value for ctc_product.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.del_flag
     *
     * @return the value of ctc_product.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.del_flag
     *
     * @param delFlag the value for ctc_product.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.product_id
     *
     * @return the value of ctc_product.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.product_id
     *
     * @param productId the value for ctc_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.product_category_id
     *
     * @return the value of ctc_product.product_category_id
     *
     * @mbggenerated
     */
    public String getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.product_category_id
     *
     * @param productCategoryId the value for ctc_product.product_category_id
     *
     * @mbggenerated
     */
    public void setProductCategoryId(String productCategoryId) {
        this.productCategoryId = productCategoryId == null ? null : productCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.product_name
     *
     * @return the value of ctc_product.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.product_name
     *
     * @param productName the value for ctc_product.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.logo
     *
     * @return the value of ctc_product.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.logo
     *
     * @param logo the value for ctc_product.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.quota
     *
     * @return the value of ctc_product.quota
     *
     * @mbggenerated
     */
    public String getQuota() {
        return quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.quota
     *
     * @param quota the value for ctc_product.quota
     *
     * @mbggenerated
     */
    public void setQuota(String quota) {
        this.quota = quota == null ? null : quota.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.rate
     *
     * @return the value of ctc_product.rate
     *
     * @mbggenerated
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.rate
     *
     * @param rate the value for ctc_product.rate
     *
     * @mbggenerated
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.ctc_describe
     *
     * @return the value of ctc_product.ctc_describe
     *
     * @mbggenerated
     */
    public String getCtcDescribe() {
        return ctcDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.ctc_describe
     *
     * @param ctcDescribe the value for ctc_product.ctc_describe
     *
     * @mbggenerated
     */
    public void setCtcDescribe(String ctcDescribe) {
        this.ctcDescribe = ctcDescribe == null ? null : ctcDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.details_describe
     *
     * @return the value of ctc_product.details_describe
     *
     * @mbggenerated
     */
    public String getDetailsDescribe() {
        return detailsDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.details_describe
     *
     * @param detailsDescribe the value for ctc_product.details_describe
     *
     * @mbggenerated
     */
    public void setDetailsDescribe(String detailsDescribe) {
        this.detailsDescribe = detailsDescribe == null ? null : detailsDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.apply_nums
     *
     * @return the value of ctc_product.apply_nums
     *
     * @mbggenerated
     */
    public Integer getApplyNums() {
        return applyNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.apply_nums
     *
     * @param applyNums the value for ctc_product.apply_nums
     *
     * @mbggenerated
     */
    public void setApplyNums(Integer applyNums) {
        this.applyNums = applyNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.fastest_loan_time
     *
     * @return the value of ctc_product.fastest_loan_time
     *
     * @mbggenerated
     */
    public String getFastestLoanTime() {
        return fastestLoanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.fastest_loan_time
     *
     * @param fastestLoanTime the value for ctc_product.fastest_loan_time
     *
     * @mbggenerated
     */
    public void setFastestLoanTime(String fastestLoanTime) {
        this.fastestLoanTime = fastestLoanTime == null ? null : fastestLoanTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.success_rate
     *
     * @return the value of ctc_product.success_rate
     *
     * @mbggenerated
     */
    public String getSuccessRate() {
        return successRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.success_rate
     *
     * @param successRate the value for ctc_product.success_rate
     *
     * @mbggenerated
     */
    public void setSuccessRate(String successRate) {
        this.successRate = successRate == null ? null : successRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.quota_range
     *
     * @return the value of ctc_product.quota_range
     *
     * @mbggenerated
     */
    public String getQuotaRange() {
        return quotaRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.quota_range
     *
     * @param quotaRange the value for ctc_product.quota_range
     *
     * @mbggenerated
     */
    public void setQuotaRange(String quotaRange) {
        this.quotaRange = quotaRange == null ? null : quotaRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.term_range
     *
     * @return the value of ctc_product.term_range
     *
     * @mbggenerated
     */
    public String getTermRange() {
        return termRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.term_range
     *
     * @param termRange the value for ctc_product.term_range
     *
     * @mbggenerated
     */
    public void setTermRange(String termRange) {
        this.termRange = termRange == null ? null : termRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.date_rate
     *
     * @return the value of ctc_product.date_rate
     *
     * @mbggenerated
     */
    public String getDateRate() {
        return dateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.date_rate
     *
     * @param dateRate the value for ctc_product.date_rate
     *
     * @mbggenerated
     */
    public void setDateRate(String dateRate) {
        this.dateRate = dateRate == null ? null : dateRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.apply_process
     *
     * @return the value of ctc_product.apply_process
     *
     * @mbggenerated
     */
    public String getApplyProcess() {
        return applyProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.apply_process
     *
     * @param applyProcess the value for ctc_product.apply_process
     *
     * @mbggenerated
     */
    public void setApplyProcess(String applyProcess) {
        this.applyProcess = applyProcess == null ? null : applyProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.apply_condition
     *
     * @return the value of ctc_product.apply_condition
     *
     * @mbggenerated
     */
    public String getApplyCondition() {
        return applyCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.apply_condition
     *
     * @param applyCondition the value for ctc_product.apply_condition
     *
     * @mbggenerated
     */
    public void setApplyCondition(String applyCondition) {
        this.applyCondition = applyCondition == null ? null : applyCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.apply_material
     *
     * @return the value of ctc_product.apply_material
     *
     * @mbggenerated
     */
    public String getApplyMaterial() {
        return applyMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.apply_material
     *
     * @param applyMaterial the value for ctc_product.apply_material
     *
     * @mbggenerated
     */
    public void setApplyMaterial(String applyMaterial) {
        this.applyMaterial = applyMaterial == null ? null : applyMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.new_product
     *
     * @return the value of ctc_product.new_product
     *
     * @mbggenerated
     */
    public String getNewProduct() {
        return newProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.new_product
     *
     * @param newProduct the value for ctc_product.new_product
     *
     * @mbggenerated
     */
    public void setNewProduct(String newProduct) {
        this.newProduct = newProduct == null ? null : newProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_product.jump_url
     *
     * @return the value of ctc_product.jump_url
     *
     * @mbggenerated
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_product.jump_url
     *
     * @param jumpUrl the value for ctc_product.jump_url
     *
     * @mbggenerated
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl == null ? null : jumpUrl.trim();
    }

    private String voLogo;
    public String getVoLogo() {
        // return voLogo;
        return new StringBuffer("").append("http://daichao.dajiabuy.cn").append("/data/web/upload/daichao/").append(logo).toString();
    }

    public void setVoLogo(String voLogo) {
        this.voLogo = voLogo;
    }
}