package com.weshare.snow.model;

import java.util.Date;

public class CtcPrroductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.product_category_id
     *
     * @mbggenerated
     */
    private String productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.product_category_name
     *
     * @mbggenerated
     */
    private String productCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_prroduct_category.product_category_url
     *
     * @mbggenerated
     */
    private String productCategoryUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.id
     *
     * @return the value of ctc_prroduct_category.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.id
     *
     * @param id the value for ctc_prroduct_category.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.create_by
     *
     * @return the value of ctc_prroduct_category.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.create_by
     *
     * @param createBy the value for ctc_prroduct_category.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.create_date
     *
     * @return the value of ctc_prroduct_category.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.create_date
     *
     * @param createDate the value for ctc_prroduct_category.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.update_by
     *
     * @return the value of ctc_prroduct_category.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.update_by
     *
     * @param updateBy the value for ctc_prroduct_category.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.update_date
     *
     * @return the value of ctc_prroduct_category.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.update_date
     *
     * @param updateDate the value for ctc_prroduct_category.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.remarks
     *
     * @return the value of ctc_prroduct_category.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.remarks
     *
     * @param remarks the value for ctc_prroduct_category.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.del_flag
     *
     * @return the value of ctc_prroduct_category.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.del_flag
     *
     * @param delFlag the value for ctc_prroduct_category.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.product_category_id
     *
     * @return the value of ctc_prroduct_category.product_category_id
     *
     * @mbggenerated
     */
    public String getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.product_category_id
     *
     * @param productCategoryId the value for ctc_prroduct_category.product_category_id
     *
     * @mbggenerated
     */
    public void setProductCategoryId(String productCategoryId) {
        this.productCategoryId = productCategoryId == null ? null : productCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.product_category_name
     *
     * @return the value of ctc_prroduct_category.product_category_name
     *
     * @mbggenerated
     */
    public String getProductCategoryName() {
        return productCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.product_category_name
     *
     * @param productCategoryName the value for ctc_prroduct_category.product_category_name
     *
     * @mbggenerated
     */
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName == null ? null : productCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_prroduct_category.product_category_url
     *
     * @return the value of ctc_prroduct_category.product_category_url
     *
     * @mbggenerated
     */
    public String getProductCategoryUrl() {
        return productCategoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_prroduct_category.product_category_url
     *
     * @param productCategoryUrl the value for ctc_prroduct_category.product_category_url
     *
     * @mbggenerated
     */
    public void setProductCategoryUrl(String productCategoryUrl) {
        this.productCategoryUrl = productCategoryUrl == null ? null : productCategoryUrl.trim();
    }

    private String voProductCategoryUrl;

    public String getVoProductCategoryUrl() {
        return new StringBuffer("").append("http://daichao.dajiabuy.cn").append("/data/web/upload/daichao/").append(productCategoryUrl).toString();
    }

    public void setVoProductCategoryUrl(String voProductCategoryUrl) {
        this.voProductCategoryUrl = voProductCategoryUrl;
    }

}