package com.weshare.snow.model;

import java.util.Date;

public class CtcUvLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_uv_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_uv_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_uv_log.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_uv_log.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_uv_log.productId
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_uv_log.id
     *
     * @return the value of ctc_uv_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_uv_log.id
     *
     * @param id the value for ctc_uv_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_uv_log.create_time
     *
     * @return the value of ctc_uv_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_uv_log.create_time
     *
     * @param createTime the value for ctc_uv_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_uv_log.mobile
     *
     * @return the value of ctc_uv_log.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_uv_log.mobile
     *
     * @param mobile the value for ctc_uv_log.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_uv_log.ip
     *
     * @return the value of ctc_uv_log.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_uv_log.ip
     *
     * @param ip the value for ctc_uv_log.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_uv_log.productId
     *
     * @return the value of ctc_uv_log.productId
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_uv_log.productId
     *
     * @param productid the value for ctc_uv_log.productId
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }
}