package com.weshare.snow.model;

import java.util.Date;

public class CtcUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.del_flag
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.user_sfz
     *
     * @mbggenerated
     */
    private String userSfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.channel_id
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.user_state
     *
     * @mbggenerated
     */
    private String userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctc_user.user_real_name_time
     *
     * @mbggenerated
     */
    private Date userRealNameTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.id
     *
     * @return the value of ctc_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.id
     *
     * @param id the value for ctc_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.create_by
     *
     * @return the value of ctc_user.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.create_by
     *
     * @param createBy the value for ctc_user.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.create_date
     *
     * @return the value of ctc_user.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.create_date
     *
     * @param createDate the value for ctc_user.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.update_by
     *
     * @return the value of ctc_user.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.update_by
     *
     * @param updateBy the value for ctc_user.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.update_date
     *
     * @return the value of ctc_user.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.update_date
     *
     * @param updateDate the value for ctc_user.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.remarks
     *
     * @return the value of ctc_user.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.remarks
     *
     * @param remarks the value for ctc_user.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.del_flag
     *
     * @return the value of ctc_user.del_flag
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.del_flag
     *
     * @param delFlag the value for ctc_user.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.user_id
     *
     * @return the value of ctc_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.user_id
     *
     * @param userId the value for ctc_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.user_name
     *
     * @return the value of ctc_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.user_name
     *
     * @param userName the value for ctc_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.user_sfz
     *
     * @return the value of ctc_user.user_sfz
     *
     * @mbggenerated
     */
    public String getUserSfz() {
        return userSfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.user_sfz
     *
     * @param userSfz the value for ctc_user.user_sfz
     *
     * @mbggenerated
     */
    public void setUserSfz(String userSfz) {
        this.userSfz = userSfz == null ? null : userSfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.user_phone
     *
     * @return the value of ctc_user.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.user_phone
     *
     * @param userPhone the value for ctc_user.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.channel_id
     *
     * @return the value of ctc_user.channel_id
     *
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.channel_id
     *
     * @param channelId the value for ctc_user.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.user_state
     *
     * @return the value of ctc_user.user_state
     *
     * @mbggenerated
     */
    public String getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.user_state
     *
     * @param userState the value for ctc_user.user_state
     *
     * @mbggenerated
     */
    public void setUserState(String userState) {
        this.userState = userState == null ? null : userState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctc_user.user_real_name_time
     *
     * @return the value of ctc_user.user_real_name_time
     *
     * @mbggenerated
     */
    public Date getUserRealNameTime() {
        return userRealNameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctc_user.user_real_name_time
     *
     * @param userRealNameTime the value for ctc_user.user_real_name_time
     *
     * @mbggenerated
     */
    public void setUserRealNameTime(Date userRealNameTime) {
        this.userRealNameTime = userRealNameTime;
    }
}